### ISSUE TITLE
env.py, line 378 causes Seg fault

### ISSUE THREAD

**Issue by thazy** [emer/leabra#1]
The last line included in the block below appears to cause a seg fault:

```
# Python type for struct env.FixedTable
class FixedTable(go.GoClass):
  """FixedTable is a basic Env that manages patterns from an etable.Table, with\neither sequential or permuted random ordering, and uses standard Trial / Epoch\nTimeScale counters to record progress and iterations through the table.\nIt also records the outer loop of Run as provided by the model.\nIt uses an IdxView indexed view of the Table, so a single shared table\ncan be used across different environments, with each having its own unique view.\n"""
  def __init__(self, *args, **kwargs):
    """
    handle=A Go-side object is always initialized with an explicit handle=arg
    otherwise parameters can be unnamed in order of field names or named fields
    in which case a new Go object is constructed first
    """
    if len(kwargs) == 1 and 'handle' in kwargs:
      self.handle = kwargs['handle']
    elif len(args) == 1 and isinstance(args[0], go.GoClass):
      self.handle = args[0].handle
    else:
      self.handle = _leabra.env_FixedTable_CTor() # line 378, env.py
```

Here is the log message after entering this statement while debugging in VSCode:
```
thazy@macbookpro ~/go/src/github.com/thazy/leabra_demo/ra25/pyra25$ pyleabra -i ra25.py
OpenGL version 4.1 NVIDIA-12.0.24 355.11.10.50.10.103
Waiting for debugger attach
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x503e400]

goroutine 36 [running]:
main.etable_IdxView_Idxs_Get(0xffffffffffffffff, 0x5a3f960)
        /Users/thazy/go/src/github.com/emer/leabra/python/leabra/leabra.go:29395 +0x30
main._cgoexpwrap_a5bdb2a0ec34_etable_IdxView_Idxs_Get(0xffffffffffffffff, 0x17e5c480)
        _cgo_gotypes.go:37142 +0x2b
main._Cfunc_Py_Main(0x3, 0xc00000c020, 0xc000000000)
        _cgo_gotypes.go:675 +0x4d
main.GoPyMainRun.func2(0x3, 0xc00000c020, 0x2)
        /Users/thazy/go/src/github.com/emer/leabra/python/leabra/leabra.go:227 +0xbd
main.GoPyMainRun()
        /Users/thazy/go/src/github.com/emer/leabra/python/leabra/leabra.go:227 +0x190
main.main.func1()
        /Users/thazy/go/src/github.com/emer/leabra/python/leabra/leabra.go:162 +0x20
github.com/goki/gi/gimain.Main.func1(0x5cdc160, 0x791ae60)
        /Users/thazy/go/src/github.com/goki/gi/gimain/gimain.go:30 +0x24
github.com/goki/gi/oswin/driver/glos.Main.func1()
        /Users/thazy/go/src/github.com/goki/gi/oswin/driver/glos/app.go:88 +0x40
created by github.com/goki/gi/oswin/driver/glos.Main
        /Users/thazy/go/src/github.com/goki/gi/oswin/driver/glos/app.go:87 +0x87
thazy@macbookpro ~/go/src/github.com/thazy/leabra_demo/ra25/pyra25$ 
```

Got here by calling `self.ConfigPats()` in `ra25.py` (from `../leabra/examples/ra25/`);  NOTE: etable.py also needs `from leabra import env` to get to `env.py` (also filed as a separate. issue)

**Comment by thazy** [comment]
CORRECTION:  Above seg fault is from entering into the call  `self.TrainEnv = env.FixedTable()`.  I had confused two different seg faults. I don't know why this one cropped up, but it was after I'd added the self.ConfigPats() call.

**Comment by rcoreilly** [comment]
This error is a classic "nil" segfault -- the `addr=0x0` means something is nil.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x503e400]
```

something is nil.. probably the Table in TrainEnv?

**Comment by thazy** [comment]
Okay.  And, I'm going to close this as I think I must have corrupted a version of ra25.py somehow.  Will go back to tracing the ConfigPats() issue.
